### PR TITLE
Bind to given port

### PR DESCRIPTION
**Pull request by xadh00m**
Hi,

we need to make the dgram port fixed in our docker environment because we explicitly bind the container port to the host port. What do you think with using the port given in the options?

Regards,
Mirko

### CODE REVIEW

**Comment by AlCalzone** [comment]
The option's port tells us which remote port to connect to. That shouldn't have any influence on the local port, especially not by default.

I don't understand why this is necessary for you, can you elaborate.

**Comment by xadh00m** [comment]
Thank you for your quick feedback!

We have a service using node-dtls-client running in a docker container. It connects to an external server which means that it sends messages to the server and the server sends messages back to the service as part of the handshake.
In our setup we have to explicitly bridge any port the service in the container is listen to to host ports. Otherwise incoming packets do not reach the service inside the container. To do that we need to know the listen port when setting up the container.

**Comment by xadh00m** [comment]
I see your point regarding the current semantic of the port variable. Maybe an optional additional `listenPort` variable might be better here?

**Comment by AlCalzone** [comment]
Yeah, that would make sense IMO. Make it optional and only use it for the `bind()` if it was provided.

**Review by AlCalzone — APPROVED** [review]

**Comment by AlCalzone** [comment]
Merged as part of 7c2d3427e0b4ab5cfdbac690b9abd571e6d615e2, I couldn't edit your branch to do the small change I wanted.

Thanks!

**Comment by xadh00m** [comment]
Amazing! Thank you very much.

**Comment by AlCalzone** [comment]
Released as v0.7.0 🎉

**Pull request closed without merging**
